"""tvb

Revision ID: f82e2f04d8a8
Revises: 
Create Date: 2022-04-19 19:12:55.536230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82e2f04d8a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bigbigshop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('digital_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entertainment_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entertainment_news_date'), 'entertainment_news', ['date'], unique=False)
    op.create_table('follow_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('j2_recommend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('latest_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_latest_news_date'), 'latest_news', ['date'], unique=False)
    op.create_table('latest_recommend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('myTVSUPER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programme_recommend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spoiler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spoilers_bar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_name'), 'station', ['name'], unique=True)
    op.create_table('upload_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('icon_path', sa.String(length=120), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('programme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('station', sa.String(length=10), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['station'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('programme_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('station', sa.String(length=10), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['station'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programme_list_time'), 'programme_list', ['time'], unique=False)
    op.create_table('forum_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('programme', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('body', sa.String(length=512), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['programme'], ['programme.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_forum_post_date'), 'forum_post', ['date'], unique=False)
    op.create_table('forum_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('body', sa.String(length=512), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post'], ['forum_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_reply_date'), 'forum_reply', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forum_reply_date'), table_name='forum_reply')
    op.drop_table('forum_reply')
    op.drop_index(op.f('ix_forum_post_date'), table_name='forum_post')
    op.drop_table('forum_post')
    op.drop_index(op.f('ix_programme_list_time'), table_name='programme_list')
    op.drop_table('programme_list')
    op.drop_table('programme')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('upload_file')
    op.drop_index(op.f('ix_station_name'), table_name='station')
    op.drop_table('station')
    op.drop_table('spoilers_bar')
    op.drop_table('spoiler')
    op.drop_table('related_link')
    op.drop_table('programme_recommend')
    op.drop_table('myTVSUPER')
    op.drop_table('latest_recommend')
    op.drop_index(op.f('ix_latest_news_date'), table_name='latest_news')
    op.drop_table('latest_news')
    op.drop_table('j2_recommend')
    op.drop_table('follow_us')
    op.drop_index(op.f('ix_entertainment_news_date'), table_name='entertainment_news')
    op.drop_table('entertainment_news')
    op.drop_table('digital_content')
    op.drop_table('bigbigshop')
    op.drop_table('application')
    op.drop_table('about_us')
    # ### end Alembic commands ###
